version: '3.8'

services:
  task-manager:
    container_name: task-manager
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_manager
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - taskmanager_network

networks:
  taskmanager_network:
    driver: bridge
